### ISSUE TITLE
Getting IndexError: list out of range from the driver.py file

### ISSUE THREAD

**Issue by jbardi** [Nico0084/py-zwave-emulator#6]
Not sure if this project has been abandoned or not, as there have been no updates in 3 years, but there are no other zwave emulators I can find.

I have added a few of my own devices from my original Zwave2mqtt cache file, and everything works fine for the first few minutes... it sees the new virtual devices I add.. waits for them to wake up... starts getting data from them, they go to sleep and wake up a few times, then the emulator crashes with the following log:

*** ACK received ****
myzwaveemulator    | Receive from controller : 0x06
myzwaveemulator    | *** writed :7 Octets --> [0x01, 0x05, 0x00, 0x13, 0x2e, 0x01, 0xc6]
myzwaveemulator    | Receive 1 Octets [0x06]
myzwaveemulator    | Pass to driver : 0x06
myzwaveemulator    | *** ACK received ****
myzwaveemulator    | Receive from controller : 0x06
myzwaveemulator    | Receive 11 Octets [0x01, 0x09, 0x00, 0x13, 0x7e, 0x02, 0x72, 0x04, 0x25, 0x2f, 0xe5]
myzwaveemulator    | Pass to driver : 0x01, 0x09, 0x00, 0x13, 0x7e, 0x02, 0x72, 0x04, 0x25, 0x2f, 0xe5
myzwaveemulator    | Receive from controller : 0x01, 0x09, 0x00, 0x13, 0x7e, 0x02, 0x72, 0x04, 0x25, 0x2f, 0xe5
myzwaveemulator    | *** writed :1 Octets --> [0x06]
myzwaveemulator    | ******************************** ProcessMsg ********************************
myzwaveemulator    | Exception in thread th_Handle_Read_Msg:
myzwaveemulator    | Traceback (most recent call last):
myzwaveemulator    |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
myzwaveemulator    |     self.run()
myzwaveemulator    |   File "/usr/lib/python2.7/threading.py", line 754, in run
myzwaveemulator    |     self.__target(*self.__args, **self.__kwargs)
myzwaveemulator    |   File "../lib/ctrlemulator.py", line 122, in waitData
myzwaveemulator    |     if self._callback is not None: self._callback(data)
myzwaveemulator    |   File "../lib/driver.py", line 622, in HandleMsg
myzwaveemulator    |     self.ProcessMsg(buffer[2:])
myzwaveemulator    |   File "../lib/driver.py", line 699, in ProcessMsg
myzwaveemulator    |     self.HandleSendDataResponse( _data, False )
myzwaveemulator    |   File "../lib/driver.py", line 1066, in HandleSendDataResponse
myzwaveemulator    |     node.HandleMsgSendDataResponse(_data)
myzwaveemulator    |   File "../lib/node.py", line 669, in HandleMsgSendDataResponse
myzwaveemulator    |     self.GetDriver.SendMsg(msg, MsgQueue.NoOp)
myzwaveemulator    |   File "../lib/driver.py", line 545, in SendMsg
myzwaveemulator    |     cc = node.GetCommandClass(_msg.GetSendingCommandClass())
myzwaveemulator    |   File "../lib/driver.py", line 1414, in GetSendingCommandClass
myzwaveemulator    |     return self.m_buffer[6]
myzwaveemulator    | IndexError: list index out of range

I have even upgraded the zwave config folder so that all the newest devices are recognized, but no dice.

**Comment by Ziocash** [comment]
Honestly I need a project like this, but I can't run it properly.
